[package]
name = "async-channel"
version = "1.5.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Async multi-producer multi-consumer channel"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/async-channel"
homepage = "https://github.com/smol-rs/async-channel"
documentation = "https://docs.rs/async-channel"
keywords = ["mpmc", "mpsc", "spmc", "chan", "futures"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
concurrent-queue = "1.2.2"
event-listener = "2.4.0"
futures-core = "0.3.8"

[dev-dependencies]
blocking = "1"
easy-parallel = "3.1.0"
futures-lite = "1.11.0"
